# Generated by install.py — do not edit by hand.
from core.secrets import SECRETS
INSTALLED_MODULE_APPS   = ['userauth']
MODULE_EXTRA_APPS       = ['django.contrib.sites', 'allauth', 'allauth.account', 'allauth.socialaccount', 'allauth.socialaccount.providers.google', 'rest_framework.authtoken', 'dj_rest_auth', 'dj_rest_auth.registration', 'rest_framework_simplejwt']
MODULE_EXTRA_MIDDLEWARE = ['allauth.account.middleware.AccountMiddleware']
MODULE_SETTINGS         = {
    'SITE_ID': 1,
    'FRONTEND_URL': 'http://localhost:5173',
    'ACCOUNT_LOGIN_METHODS': {'username': True},
    'ACCOUNT_SIGNUP_FIELDS': ['email*', 'username*', 'password1*', 'password2*'],
    'ACCOUNT_EMAIL_VERIFICATION': 'none',
    'REST_AUTH': {'USE_JWT': True, 'JWT_AUTH_COOKIE': None, 'TOKEN_MODEL': None},
    'EMAIL_BACKEND': 'django_ses.SESBackend',
    'RECAPTCHA_SITE_KEY': SECRETS.get('RECAPTCHA_SITE_KEY', ''),
    'RECAPTCHA_SECRET_KEY': SECRETS.get('RECAPTCHA_SECRET_KEY', ''),
    'RECAPTCHA_PROJECT_ID': SECRETS.get('RECAPTCHA_PROJECT_ID', ''),
    'RECAPTCHA_THRESHOLD': 0.5,
}
