"""
Shared settings for all environments.
Environment-specific files (development.py, production.py) import from here.
"""
from pathlib import Path
from datetime import timedelta
from django.core.exceptions import ImproperlyConfigured
from core.secrets import SECRETS

BASE_DIR = Path(__file__).resolve().parent.parent.parent
REPO_ROOT = BASE_DIR.parent.parent  # core/backend -> core -> repo root

APP_NAME = SECRETS.APP_NAME

# Required -- fails loudly at import time (see core/secrets.py) rather than
# running with an unsafe default.
SECRET_KEY = SECRETS.SECRET_KEY

DEBUG = False  # Always overridden by environment settings.

ALLOWED_HOSTS = SECRETS.get('ALLOWED_HOSTS', ['localhost', '127.0.0.1'])

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'rest_framework',
    'corsheaders',
    'core_app',
    'rest_framework_simplejwt.token_blacklist',
]

MIDDLEWARE = [
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'core.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'core.wsgi.application'

AUTH_USER_MODEL = 'core_app.CustomUser'

AUTH_PASSWORD_VALIDATORS = [
    {'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator'},
    {'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator'},
    {'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator'},
    {'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator'},
]

REST_FRAMEWORK = {
    'DEFAULT_RENDERER_CLASSES': [
        'rest_framework.renderers.JSONRenderer',
    ],
    'DEFAULT_AUTHENTICATION_CLASSES': [
        'rest_framework_simplejwt.authentication.JWTAuthentication',
        'rest_framework.authentication.SessionAuthentication',
    ],
    'DEFAULT_PERMISSION_CLASSES': [
        'rest_framework.permissions.IsAuthenticated',
    ],
    'EXCEPTION_HANDLER': 'core.error_handlers.api_exception_handler',
    'DEFAULT_PARSER_CLASSES': [
        'rest_framework.parsers.JSONParser',
        'rest_framework.parsers.FormParser',
        'rest_framework.parsers.MultiPartParser',
    ]
}

SIMPLE_JWT = {
    'ACCESS_TOKEN_LIFETIME':  timedelta(hours=1),
    'REFRESH_TOKEN_LIFETIME': timedelta(days=7),
    'ROTATE_REFRESH_TOKENS':  True,
}

LANGUAGE_CODE = 'en-us'
TIME_ZONE = 'America/Los_Angeles'
USE_I18N = True
USE_TZ = True

STATIC_URL = '/static/'
STATIC_ROOT = BASE_DIR / 'staticfiles'

MEDIA_URL  = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'

LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'handlers': {
        'console': {
            'class': 'logging.StreamHandler',
        },
    },
    'root': {
        'handlers': ['console'],
        'level': 'ERROR',
    },
}

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# ---------------------------------------------------------------------------
# Installed modules
#
# INSTALLED_MODULE_APPS / MODULE_EXTRA_APPS / MODULE_EXTRA_MIDDLEWARE /
# MODULE_REQUIRED_SETTINGS are (re)generated by `install.py` into the
# gitignored core/installed_modules.py — see CLAUDE.md. MODULE_REQUIRED_SETTINGS
# is just the list of setting *names* each enabled module declares in its
# module.json `required_settings`; the values live below, by hand, in one
# place, rather than being generated.
# ---------------------------------------------------------------------------

try:
    from core.installed_modules import (
        INSTALLED_MODULE_APPS,
        MODULE_EXTRA_APPS,
        MODULE_EXTRA_MIDDLEWARE,
        MODULE_REQUIRED_SETTINGS,
    )
except ImportError:
    INSTALLED_MODULE_APPS = []
    MODULE_EXTRA_APPS = []
    MODULE_EXTRA_MIDDLEWARE = []
    MODULE_REQUIRED_SETTINGS = []

INSTALLED_APPS += INSTALLED_MODULE_APPS + MODULE_EXTRA_APPS
MIDDLEWARE += MODULE_EXTRA_MIDDLEWARE

# ---------------------------------------------------------------------------
# Module settings (values)
#
# Every setting an enabled module needs lives here, grouped by module. Secret
# or environment-specific values are read via SECRETS.get(...) (see
# core/secrets.py / secrets.json.example); plain config constants are literal.
# ---------------------------------------------------------------------------

# userauth
SITE_ID                       = 1
FRONTEND_URL                  = SECRETS.get('FRONTEND_URL', 'http://localhost:5173')
ACCOUNT_LOGIN_METHODS         = {'username': True}
ACCOUNT_SIGNUP_FIELDS         = ['email*', 'username*', 'password1*', 'password2*']
ACCOUNT_EMAIL_VERIFICATION    = 'none'
REST_AUTH                     = {'USE_JWT': True, 'JWT_AUTH_COOKIE': None, 'TOKEN_MODEL': None}
EMAIL_BACKEND                 = 'django_ses.SESBackend'
RECAPTCHA_API_KEY             = SECRETS.get('RECAPTCHA_API_KEY', '')
RECAPTCHA_SITE_KEY            = SECRETS.get('RECAPTCHA_SITE_KEY', '')
RECAPTCHA_SECRET_KEY          = SECRETS.get('RECAPTCHA_SECRET_KEY', '')
RECAPTCHA_PROJECT_ID          = SECRETS.get('RECAPTCHA_PROJECT_ID', '')
RECAPTCHA_THRESHOLD           = 0.5

SOCIALACCOUNT_PROVIDERS = {
    'google': {
        'APP': {
            'client_id': SECRETS.get('GOOGLE_CLIENT_ID', ''),
            'secret':    SECRETS.get('GOOGLE_CLIENT_SECRET', ''),
            'key':       '',
        },
        'SCOPE': ['profile', 'email'],
        'AUTH_PARAMS': {'access_type': 'online'},
    }
}

AWS_SES_ACCESS_KEY      = SECRETS.get('AWS_SES_ACCESS_KEY', '')
AWS_SES_SECRET_KEY      = SECRETS.get('AWS_SES_SECRET_KEY', '')
AWS_SES_REGION_NAME     = SECRETS.get('AWS_SES_REGION_NAME', 'us-east-1')
AWS_SES_REGION_ENDPOINT = f'email.{AWS_SES_REGION_NAME}.amazonaws.com'
DEFAULT_FROM_EMAIL      = SECRETS.get('DEFAULT_FROM_EMAIL', '')

# interest
SITE_ADMIN_EMAIL = SECRETS.get('SITE_ADMIN_EMAIL', '')

# billing (Stripe)
STRIPE_SECRET_KEY      = SECRETS.get('STRIPE_SECRET_KEY', '')
STRIPE_PUBLISHABLE_KEY = SECRETS.get('STRIPE_PUBLISHABLE_KEY', '')
STRIPE_WEBHOOK_SECRET  = SECRETS.get('STRIPE_WEBHOOK_SECRET', '')
STRIPE_SUCCESS_URL     = SECRETS.get('STRIPE_SUCCESS_URL', '')
STRIPE_CANCEL_URL      = SECRETS.get('STRIPE_CANCEL_URL', '')

# booking
BOOKING_PAYMENT_HOLD_MINUTES          = 20
BOOKING_PROMOTION_HOLD_HOURS          = 24
BOOKING_TEMPLATE_GENERATE_WEEKS_AHEAD = 8

# files
FILES_AWS_ACCESS_KEY_ID       = SECRETS.get('FILES_AWS_ACCESS_KEY_ID', '')
FILES_AWS_SECRET_ACCESS_KEY   = SECRETS.get('FILES_AWS_SECRET_ACCESS_KEY', '')
FILES_AWS_REGION              = 'us-east-1'
FILES_S3_PRESIGNED_URL_EXPIRY = 3600
FILES_CI_API_KEY              = SECRETS.get('FILES_CI_API_KEY', '')

# fileupload
AWS_FILEUPLOAD_ACCESS_KEY  = SECRETS.get('AWS_FILEUPLOAD_ACCESS_KEY', '')
AWS_FILEUPLOAD_SECRET_KEY  = SECRETS.get('AWS_FILEUPLOAD_SECRET_KEY', '')
AWS_FILEUPLOAD_S3_REGION   = SECRETS.get('AWS_FILEUPLOAD_S3_REGION', '')
AWS_UPLOAD_BUCKET          = SECRETS.get('AWS_UPLOAD_BUCKET', '')
AWS_PROCESSED_BUCKET       = SECRETS.get('AWS_PROCESSED_BUCKET', '')
AWS_S3_REGION              = 'us-east-1'
FILEUPLOAD_WEBHOOK_SECRET  = SECRETS.get('FILEUPLOAD_WEBHOOK_SECRET', '')

# licensing
LICENSE_APP_SECRET               = SECRETS.get('LICENSE_APP_SECRET', '')
LICENSE_RSA_PRIVATE_KEY_PATH     = SECRETS.get('LICENSE_RSA_PRIVATE_KEY_PATH', '')
LICENSE_RSA_PUBLIC_KEY_PATH      = SECRETS.get('LICENSE_RSA_PUBLIC_KEY_PATH', '')
LICENSE_DEFAULT_MAX_MACHINES     = 1
LICENSE_DEFAULT_OFFLINE_TTL_DAYS = 30

# ---------------------------------------------------------------------------
# Fail loudly (like SECRET_KEY above) if an enabled module needs a setting
# that isn't defined above, instead of silently running without it.
# ---------------------------------------------------------------------------

_missing_settings = [name for name in MODULE_REQUIRED_SETTINGS if name not in globals()]
if _missing_settings:
    raise ImproperlyConfigured(
        'Enabled modules require settings not defined in '
        'core/backend/core/settings/base.py: ' + ', '.join(_missing_settings)
    )
