// Generated by install.py -- do not edit by hand.

import * as siteModule from '../../../site/frontend/src/index.js';
import * as userauthModule from '@modules/userauth';

export const moduleRoutes = [
  ...(siteModule.routes ?? []),
  ...(userauthModule.routes ?? []),
];

export const moduleNavItems = [
  ...(siteModule.navItems ?? []),
  ...(userauthModule.navItems ?? []),
];

export const moduleProviders = [
  ...(siteModule.providers ?? []),
  ...(userauthModule.providers ?? []),
];

export const moduleNavbarEnd = [
  ...(siteModule.navbarEnd ?? []),
  ...(userauthModule.navbarEnd ?? []),
];

export const moduleAdminCards = [
  ...(siteModule.adminCards ?? []),
  ...(userauthModule.adminCards ?? []),
];

export const moduleUserSections = [
  ...(siteModule.userSections ?? []),
  ...(userauthModule.userSections ?? []),
];

export const moduleHomeSections = [
  ...(siteModule.homeSections ?? []),
  ...(userauthModule.homeSections ?? []),
];
